### ISSUE TITLE
Driver Not found

### ISSUE THREAD

**Issue by echonikul** [senthalan2/react-native-rdservice-fingerprintscanner#1]
isDeviceDriverFound": false, "message": "Device Driver not found", "status": 0 ,after connecting to mantra ,driver not found is coming

**Comment by senthalan2** [comment]
you should install the mantra device driver from play store.

**Comment by NamanCsc** [comment]
I’m facing the same issue even after installing the Myntra L1 driver, and I’m still encountering an error.
https://play.google.com/store/apps/details?id=com.mantra.rdservice
