### ISSUE TITLE
Sir please solve this problem. . . . 

### ISSUE THREAD

**Issue by goutam11mondal** [senthalan2/react-native-rdservice-fingerprintscanner#1]
![Capture](https://user-images.githubusercontent.com/40601308/168406627-fc8bcd93-1e99-467a-9f99-28773019c984.PNG)

package.json Details:

{
  "name": "my-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~45.0.0",
    "expo-status-bar": "~1.3.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-rdservice-fingerprintscanner": "^1.1.7",
    "react-native-web": "0.17.7"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true,
  "author": "",
  "license": "ISC",
  "description": ""
}

**Comment by senthalan2** [comment]
> ![Capture](https://user-images.githubusercontent.com/40601308/168406627-fc8bcd93-1e99-467a-9f99-28773019c984.PNG)
> 
> package.json Details:
> 
> { "name": "my-app", "version": "1.0.0", "main": "node_modules/expo/AppEntry.js", "scripts": { "start": "expo start", "android": "expo start --android", "ios": "expo start --ios", "web": "expo start --web", "eject": "expo eject" }, "dependencies": { "expo": "~45.0.0", "expo-status-bar": "~1.3.0", "react": "17.0.2", "react-dom": "17.0.2", "react-native": "0.68.2", "react-native-rdservice-fingerprintscanner": "^1.1.7", "react-native-web": "0.17.7" }, "devDependencies": { "@babel/core": "^7.12.9" }, "private": true, "author": "", "license": "ISC", "description": "" }

After the package installation, follow the below steps,

1. npm start -- --reset-cache
2. npm run android

It works fine.
