### ISSUE TITLE
Rd service not detected 

### ISSUE THREAD

**Issue by Abhishek25031991** [senthalan2/react-native-rdservice-fingerprintscanner#3]
I installed Myntra app in my android and use the function getDeviceInfo() but function always give response driver not found and status -1

**Comment by senthalan2** [comment]
Make sure that the device is connected properly and the Device driver is installed correctly on your Mobile.
Share your Device Information.

**Comment by Abhishek25031991** [comment]
Do i need to pass device package name in the function

**Comment by senthalan2** [comment]
No. This package can automatically get that device package name using the device driver.

**Comment by Abhishek25031991** [comment]
ok

**Comment by senthalan2** [comment]
👍
